name: CI

on:
  pull_request:
    branches: [main]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1

  test_build:
    needs: pre_commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [alpine, ubuntu, ubi, suse, node, oraclelinux, openssl]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Test build ${{ matrix.image }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile.${{ matrix.image }}
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
