name: Release

on:
  push:
    branches: [main]

env:
  DOCKER_USER: psazevedo

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    environment: release
    name: "Bump version and create changelog with commitizen"
    outputs:
      bump_version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  build_and_push:
    needs: bump_version
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        image: [alpine, ubuntu, ubi, suse, node, oraclelinux, openssl]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multiarch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile.${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.DOCKER_USER }}/${{ matrix.image }}:latest
            ${{ env.DOCKER_USER }}/${{ matrix.image }}:${{ needs.bump_version.outputs.bump_version || 'latest' }}
