name: Renovate

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v43.0.11
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
